[package]
name = "truc"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_app_compute = "0.16.0"
rand = "0.9.2"

[profile.release]
codegen-units = 1
lto = "thin"
[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"